### ISSUE TITLE
Kannada Article : Corrections needed

### ISSUE THREAD

**Issue by chutki-25** [AdarshRevankar/Spectrum2019#1]
1. Kannada articles: Please follow uniformity for the students' name. Some are mentioned in kannada, and some in English. Please see to that.

Rest everything seems fine as of now :-)

**Comment by AdarshRevankar** [comment]
I need information of **Year : Branch** of these students
_1. Abhishek Anchan
2. Surabhi K
3. [ Person who wrote - " Kaalaye Tasmaye nahama" ]_

**Comment by chutki-25** [comment]
1.Abhishek Anchan-3rd year ECE

3.Kaalaye Tasmaye Namaha - "Aathma Sanchari"

**Comment by AdarshRevankar** [comment]
Surabhi details are required

**Comment by AdarshRevankar** [comment]
Issue resolved
